### ISSUE TITLE
How to run eval with custom data?

### ISSUE THREAD

**Issue by ReeseL** [FangjinhuaWang/PatchmatchNet#16]
Hi,

Thanks for your excellent work!  The eval examples you provided :TANK_TESTING, ETH3d_TESTING, DTU_TESTING, but if I want to test my own data,how to do it?
 
Reese

**Comment by FangjinhuaWang** [comment]
Hello:

Currently, following MVSNet, we support building a custom dataset from COLMAP's reconstruction results (also for our ETH3D). 

Suppose that you have a folder of images without any other information such as pose, you can first run COLMAP (SfM) to get the sparse reconstruction results (undistorted images, poses, 3D points).  I just update the codes, you can use 'colmap_input.py' to convert the results from COLMAP into the same format of the datasets we provide. I also add some evaluation codes for the custom dataset. Please read the ReadMe for more details. 

Hope this helps!
