### ISSUE TITLE
How are the 10 best source views selected?

### ISSUE THREAD

**Issue by morsingher** [FangjinhuaWang/PatchmatchNet#19]
Hi, 

first of all: awesome work! 

I have a question about view selection. You store the view selection result in pair.txt for each dataset, however I couldn't find any reference to how you actually select those 10 source views. If I interpreted correctly what you mean in section 4.2, I guess you compute the view selection score as in MVSNet (a Gaussian function of the triangulation angle between sparse points and camera centers) and pick the best 10 views for each reference.

Is it correct?

Thank you in advance,

Marco.

**Comment by FangjinhuaWang** [comment]
Hi,

Yes, you are correct. the view selection is the same as MVSNet. You can find the code for view selection in 'colmap_input.py' from Line 380-410.
