### ISSUE TITLE
How to compute initial depth range?

### ISSUE THREAD

**Issue by morsingher** [FangjinhuaWang/PatchmatchNet#21]
Hi,

sorry to bother you again, but I have a question on how you preprocess the datasets to get the min and max value for the depth range. My guess is that you compute them based on the sparse point cloud obtained from SfM, but it would be nice if you could provide more details about this point. 

From what I understood, it is done in lines 360-378 of colmap_input.py: you transform the point cloud in the local frame of the reference image i, compute the distance along the z-axis from the camera center and then pick the min and max value. Is it correct? Why do you "relax" the depth range (lines 373-374)?

Thank you in advance,

Marco.

**Comment by FangjinhuaWang** [comment]
Hi,

You are correct. The depth range is based on the sparse point cloud from COLMAP. As explained in Readme, we basically borrow the code (colmap_input.py) to generate the input from MVSNet. The relaxation is used to remove some noise in the sparse reconstruction.
