### ISSUE TITLE
Little bug (maybe a typo?) when loading custom dataset

### ISSUE THREAD

**Issue by morsingher** [FangjinhuaWang/PatchmatchNet#22]
Hi, I'm opening this just to let you know that at line 46 of datasets/custom.py I think there is a small bug (probably just a typo):

depth_max = float(lines[11].split()[3])

should actually be:

depth_max = float(lines[11].split()[1])

Best regards!

**Comment by FangjinhuaWang** [comment]
Hi,

Thanks for pointing it out! It is already fixed.
