### ISSUE TITLE
may be a typo in dtu_yao_eval.py

### ISSUE THREAD

**Issue by LuckyOne09** [FangjinhuaWang/PatchmatchNet#23]
Hi, thank you for your great work firstly.
I found that there may be a typo in dtu_yao_eval.py
I think the line 100 in dtu_yao_eval.py should be: 
```             
proj_mat_filename = os.path.join(self.datapath, '{}/cams/{:0>8}_cam.txt'.format(scan, vid))
```
not 
```
proj_mat_filename = os.path.join(self.datapath, '{}/cams_1/{:0>8}_cam.txt'.format(scan, vid))
```

Best regards!

**Comment by FangjinhuaWang** [comment]
Hi,

In the DTU evaluation set that we provide, we name the camera folder as "cams_1".

**Comment by LuckyOne09** [comment]
Ohhh, sorry. Thank you for your reply.
I use the DTU evaluation set provided by https://github.com/YoYo000/MVSNet.
