### ISSUE TITLE
Outdoor scenarios

### ISSUE THREAD

**Issue by morsingher** [FangjinhuaWang/PatchmatchNet#24]
Hi,

I have been playing around with this repo for a while and I have a couple of questions: 

1) I have noticed that the quality of the point cloud is much worse in outdoor scenarios with poor features (like the meadow scene in ETH3D). Also, I have tested it on a custom urban dataset where a large part of the image is either the vehicle itself or textureless areas like the road and the sky, and performances degrade even more. My question is: do you think that the network is flexible enough to handle this kind of situation (i.e. I just need to tune some parameters in eval.sh)? If the answer is no, do you think that re-training the network with outdoor datasets (like http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction) would help?

2) Since my own urban dataset is pretty challenging, I tried with something easier like the scene "2011_09_26_drive_0005" from http://www.cvlibs.net/datasets/kitti/raw_data.php, and I processed it with COLMAP (no issues up to here). However, I get a weird concatenation error during the feature extraction phase (line 47 of models/net.py). I guess that the problem is in the form factor of the images, which have size 1242 x 375, for two reasons:
a) I have no issues with other more "common" formats, even for custom datasets. 
b) I have changed the size accordingly in both eval_custom.py and datasets/custom.py, and the weird thing is that if I choose a more balanced format for the same data, then the code runs smoothly.
Do you have any idea why this happens and how to fix it?

Thank you in advance for the help and for the awesome work,

Marco.

**Comment by FangjinhuaWang** [comment]
1. I think training on large-scale outdoor datasets, such as BlendedMVS [https://github.com/YoYo000/BlendedMVS](url), is helpful. The DTU dataset that we use for training is an indoor environment.

2. You need to make sure the height and width is divisable by 8. The feature extraction has downsampling and upsampling.

**Comment by morsingher** [comment]
Thank you for the answers. May I suggest to put point 2 in the readme? I think it would help other users :)

**Comment by FangjinhuaWang** [comment]
Yes, I agree. It is updated.

**Comment by Alive-zyxs** [comment]
@morsingher Sorry to bother you,have you already tried training on an outdoor dataset? If so, what about the results?Thanks very much.
