### ISSUE TITLE
Training problem?

### ISSUE THREAD

**Issue by ReeseL** [FangjinhuaWang/PatchmatchNet#25]
Hi,wang
Thanks for your excellent work! When I train my custom dataset, loss suddenly changes to NaN on the way descent.
I'm tring to find reasons. 
I have a question that your dtu dataset has a same depth range [dmin,dmax], but my dataset' depth range is different in every image. I don't know whether defferent  depth range  is ok for training. Could you  give me some advices ?

**Comment by FangjinhuaWang** [comment]
Hi,
I do not think the different depth range may cause a training problem. I did some experiments on BlendedMVS before, where the depth range are different for different images.

**Comment by ReeseL** [comment]
@FangjinhuaWang  
Ok, thanks for your reply.
