### ISSUE TITLE
the huge file size of the point clouds after fusion

### ISSUE THREAD

**Issue by Zhu980805** [FangjinhuaWang/PatchmatchNet#26]
The ply files after depth fusion are almost greater than 200mb and even close to 1gb while the gt point files are almost less than 200mb
for example，
patchmatchnet001_l3.ply is 862.8mb  and stl001_total.ply is 77.8mb.

Is this situation normal？
Thank you for your outstanding work and look forward to your reply.

**Comment by FangjinhuaWang** [comment]
Hi,

I think this is the correct reproduced result since the input images are very large (1600*1200). The ground truth is collected via a scanner and very sparse. During evaluation, the point cloud will be downsampled automatically.

**Comment by Zhu980805** [comment]
OK, thanks for your reply.
