### ISSUE TITLE
Question about Adaptive propagation.

### ISSUE THREAD

**Issue by KyuminHwang** [FangjinhuaWang/PatchmatchNet#27]
Hi, First of all thanks for your great efforts on this research.

I have a question about adaptive propagation. 
**In model/patchmatch.py at line from 79 to 82.**

` 
        propogate_depth_sample = F.grid_sample(depth_sample[:, num_depth // 2,:,:].unsqueeze(1), 
                                    grid, 
                                    mode='bilinear',
                                    padding_mode='border')
`

Is there have any intuition or knowledge about _**num_depth//2**_ ?
I guessed that **_num//depth2_** is the center of hypothesis planes that is equivalent to zero depth.  
I cannot understand this part, clearly. 
Could you explain for me ? 

Thank you for sharing the research results !

**Comment by FangjinhuaWang** [comment]
Hi,

For each pixel, the input of propagation is the set of hypotheses that are sampled around the estimation **d** from previous iteration. The index "num_depth//2" corresponds to this estimation **d**, the other indices correspond to the new samples around **d**.
