### ISSUE TITLE
empty ply files

### ISSUE THREAD

**Issue by stillwang96** [FangjinhuaWang/PatchmatchNet#34]
Hi, when I run the eval part using given pretrained model, the geo_mask and final_mask are all 0, and the ply files are empty in meshlab, how can I deal with the problem? Thank you!

**Comment by FangjinhuaWang** [comment]
Hi,
What's the data that you use? I think you use your own data. There is no problem like this on the datasets that we provide. Could you check whether there are any problems in your own data, especially intrinsics, extrinsics and your given depth range?

**Comment by stillwang96** [comment]
Hi, I just used the DTU dataset, and may I have your e-mail address and send some screenshots to help me see what the problem is?

**Comment by FangjinhuaWang** [comment]
ok, it is jasonwangfang1@gmail.com. What is the DTU dataset that you use? The DTU dataset that we provide is a little different (the camera file) from the one from MVSNet.

**Comment by FangjinhuaWang** [comment]
I test the current version of code (fix some small bugs in the former two pushes from another contributor). There is no problem in the masks.

**Comment by FrankGoTo** [comment]
> Hi, I just used the DTU dataset, and may I have your e-mail address and send some screenshots to help me see what the problem is?

I change DTU dataset  camera folder name "cams" to "cams_1" directly and got the empty PLY file too.  Can you share the solution for this issue?

**Comment by FrankGoTo** [comment]
> > > Hi, I just used the DTU dataset, and may I have your e-mail address and send some screenshots to help me see what the problem is?
> > 
> > 
> > I change DTU dataset camera folder name "cams" to "cams_1" directly and got the empty PLY file too. Can you share the solution for this issue?
> 
> Download the DTU dataset this project provides. Its a little different from the normal one in the cam txt.

Yes, its a little different from the previous dataset. It work  thank you very much !!

**Comment by FangjinhuaWang** [comment]
Yes, it is a little different from the original one from MVSNet since we do not need the "depth_interval" and "num_of_depth" in the original cam file from MVSNet. So we remove it.
