### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by ss2lyf** [FangjinhuaWang/PatchmatchNet#35]
CUDA 11.1 and pytorch 1.8.1 are installed on my computer, when I run train.sh, the training process did not start , and the error message is "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!" 
**The solution is as follows：**
add .cpu() after "loss = loss + F.smooth_l1_loss(depth1, depth2, reduction="mean")" in "PatchmatchNet/models/net.py" as "loss = loss + F.smooth_l1_loss(depth1, depth2, reduction="mean").cpu()"

**Comment by FangjinhuaWang** [comment]
Hi,

Sorry about this. I fix several bugs in the pushes from other contributors yesterday. I think the bug that the loss tensor is on cpu induced your problem. There should be no problem now in the latest version.

**Comment by ss2lyf** [comment]
> Hi,
> 
> Sorry about this. I fix several bugs in the pushes from other contributors yesterday. I think the bug that the loss tensor is on cpu induced your problem. There should be no problem now in the latest version.

I tried the new code and everything works fine！

**Comment by ss2lyf** [comment]
> Hi,
> 
> Sorry about this. I fix several bugs in the pushes from other contributors yesterday. I think the bug that the loss tensor is on cpu induced your problem. There should be no problem now in the latest version.

I tried the new code and everything works fine！Thanks a lot!
