### ISSUE TITLE
Question about scaling DTU intrinsics

### ISSUE THREAD

**Issue by morsingher** [FangjinhuaWang/PatchmatchNet#36]
Hi, I was wondering what the following comment means:

https://github.com/FangjinhuaWang/PatchmatchNet/blob/65ff2b452da5dbecdee92eaa2ab1fb7fea5cb447/datasets/dtu_yao.py#L170

It seems that you assume intrinsics in training file to be already downscaled by a factor of 4, but in your preprocessed DTU datasets, intrinsics are as follows:

intrinsic
2892.33 0 823.205
0 2883.18 619.072
0 0 1

which match the ones in the MVSNet repo and they seem to match the original resolution of 1600 x 1200. I checked the other datasets and you correctly do:

intrinsics[:2,:] *= 0.125

at stage 3, rather than *= 0.5 as you do for DTU. Could you please clarify on this point? I'm asking since I'm adding support for training on BlendedMVS and I would like to make things right. Thank you in advance!

**Comment by FangjinhuaWang** [comment]
Hi,

The training camera parameters that is read in is here (https://github.com/FangjinhuaWang/PatchmatchNet/blob/65ff2b452da5dbecdee92eaa2ab1fb7fea5cb447/datasets/dtu_yao.py#L162), which is already scaled for the image size of 1/4.

**Comment by morsingher** [comment]
Hi, thanks for the answer. So the following intrinsics (e.g from Cameras_1/train/00000000_cam.txt)::

intrinsic
2892.33 0 823.205
0 2883.18 619.072
0 0 1

are not expressed in unit pixels, right? If you consider full size to be 640 x 512 and 1/4 size to be 160 x 128, they seem to be expressed in "units" of 0.1 pixels. Otherwise the principal point would be outside the image plane.

**Comment by FangjinhuaWang** [comment]
The camera file that I provide "Cameras_1/train" is the same as MVSNet, it looks like:

intrinsic
361.54126 0.0 82.90063 
0.0 360.3975 66.38387 
0.0 0.0 1.0

**Comment by morsingher** [comment]
Sorry, you are right. I got confused by the layout of the folder. Closing as solved.
