### ISSUE TITLE
FileNotFoundError when testing on DTU

### ISSUE THREAD

**Issue by YuhsiHu** [FangjinhuaWang/PatchmatchNet#39]
Hi, thank you for your excellent work!
I download the the preprocessed DTU testing dataset and run eval.sh. After scan1 is finished, some errors show as follows:
>>saving the final model to ./outputs/patchmatchnet001_l3.ply
Traceback (most recent call last):
  File "eval.py", line 353, in <module>
    args.geo_pixel_thres, args.geo_depth_thres, args.photo_thres, img_wh)
  File "eval.py", line 244, in filter_depth
    ref_depth_est = read_pfm(os.path.join(out_folder, 'depth_est/{:0>8}.pfm'.format(ref_view)))[0]
  File "/PatchmatchNet/datasets/data_io.py", line 20, in read_pfm
    file = open(filename, "rb") # treat as binary and read-only
FileNotFoundError: [Errno 2] No such file or directory: './outputs/scan4/depth_est/00000000.pfm'

The files of scan1 are good, but there is no other scanX folders under ./outputs

**Comment by FangjinhuaWang** [comment]
Thanks for pointing this out. I did some small test (only evaluate on scan 1) before last update. Now it should be ok.

**Comment by YuhsiHu** [comment]
Thanks! Now the pointcloud of other folders can be generated.
