### ISSUE TITLE
Reproduce results in DTU dataset

### ISSUE THREAD

**Issue by Tangshitao** [FangjinhuaWang/PatchmatchNet#41]
Hi, I cannot reproduce the results on DTU dataset. I first run train.sh, with 2 gpus and a batchsize of 4 and evaluation the model with eval.sh. However, I got a result of (0.453(Acc) 0.294(comp) 0.374(overall), which is far worse than the paper reported (0.427 0.277 0.352). Can you provide the pretrained weight that can achieve the results in paper?

**Comment by FangjinhuaWang** [comment]
The pretrained weight is already included (folder 'checkpoints').
