### ISSUE TITLE
reproduce the results

### ISSUE THREAD

**Issue by crazycodebiu** [FangjinhuaWang/PatchmatchNet#46]
Hi, Thank you for your excellent work. I have some questions about how to reproduce the results on DTU dataset.
I want to know whether the final score(Acc.   Comp.  Overall.) is the average result of calculating 22 point cloud files .
These 22 point cloud files are 22 numbers in UsedSets under the path  \PatchmatchNet-main\evaluations\dtu\BaseEvalMain_web.m
Hope to get your reply !

**Comment by FangjinhuaWang** [comment]
Hi,
Yes, the final scores is the average result on 22 scenes (following other learning-based MVS methods). The 22 numbers in the matlab file represent the index of these scenes. To reproduce the result, you can follow readme. I think it is clear enough.

**Comment by crazycodebiu** [comment]
Thank you for your reply. 
I am trying to run the BaseEvalMain_web.m code you provided in matlab.
But  I found that the process of calculating the score is very slow. Is this normal?

**Comment by FangjinhuaWang** [comment]
Yes, it is because the point cloud is usually quite dense (on my computer, the time is about 20 min for a point cloud with a size around 800MB).

**Comment by crazycodebiu** [comment]
Thank you very much for your patience. I have successfully solved the problem and got the corresponding score. 
Thank you very much for your help!
