### ISSUE TITLE
depth_img生成为空的 (depth_img is empty)

### ISSUE THREAD

**Issue by XQQ1072448274** [FangjinhuaWang/PatchmatchNet#47]
您好，我在复现的时候，运行eval.sh，生成的outputs里面每个scan中depth_img文件都是空的，是什么原因呢？感谢感谢

**Comment by initialneil** [comment]
> 这是因为深度图不正确，没有通过两个filtering。你是用我提供的DTU测试数据集吗？我提供的DTU测试数据集和MVSNet提供的有一点差别（相机文件简化了一下）。

I had the same problem of all confidence less than 0.5 and the depth were all wrong (just noise) using the DTU data you provided with `eval.sh`.

I tested recent commits:
- ec9819c4a6504753522adcafb70dc412cdb1d04d gives the wrong results
- 4bf06ec8042bb4d15c1ab330aae3629aee593caf is correct
    - [line 199 of patchmatch.py](https://github.com/FangjinhuaWang/PatchmatchNet/blob/4bf06ec8042bb4d15c1ab330aae3629aee593caf/models/patchmatch.py#L199) have dimension error. Fixed by adding `unsqueeze`: `similarity = (warped_feature * ref_feature.unsqueeze(3)).mean(2)`

So I guess there're errors in [pull request #44](https://github.com/FangjinhuaWang/PatchmatchNet/pull/45).

**Comment by anmatako** [comment]
@XQQ1072448274 @initialneil this is now fixed in #49
