### ISSUE TITLE
RuntimeError:

### ISSUE THREAD

**Issue by Run-1123** [FangjinhuaWang/PatchmatchNet#48]
File "/home/mjju/code/MVS_DL/PatchmatchNet/models/patchmatch.py", line 100, in forward
    depth_sample = 1.0 / depth.detach() + inverse_depth_interval * depth_sample
RuntimeError: The size of tensor a (10) must match the size of tensor b (80) at non-singleton dimension 3

I added something to your structure. Where is the wrong parameter setting for this error?

**Comment by FangjinhuaWang** [comment]
Hi. The pull request #44, #45 merged yesterday (which are mainly related to COLMAP stuff) has some issues inside. We are looking into this. Currently, please have a try with #43, which is tested correctly.

**Comment by anmatako** [comment]
@Run-1123  this is fixed in #49
