### ISSUE TITLE
How do you test the memory usage of your method?

### ISSUE THREAD

**Issue by MiZhenxing** [FangjinhuaWang/PatchmatchNet#51]
Hi, Thank you very much for your excellent work. 
I have a question that how you get the memory usage of your model. From the [document ](https://pytorch.org/docs/stable/generated/torch.cuda.max_memory_allocated.html) of Pytorch that we could use torch.cuda.reset_peak_memory_stats() and torch.cuda.max_memory_allocated() to calculate the memory used by Pytorch. So did you use this method to get the memory usage? If so, where did you put these two functions? 
Thank you very much!

**Comment by FangjinhuaWang** [comment]
Hi,

I use nvidia-smi or nvgpu, the python warpper of nvidia-smi.
