### ISSUE TITLE
Could you please provide some more detailed data of Fig.1 in your paper?

### ISSUE THREAD

**Issue by qtz980805** [FangjinhuaWang/PatchmatchNet#55]
Thanks for your outstanding work and rich experimental verification!

For Figure. 1 in your paper, there are intuitive comparison with SOTA methods, in terms of overall error, runtime and memory consumption. But would mind please providing some more detailed data, such as the specific value of overall error of your method and other SOTA methods with image size 1152x864.

Thanks a lot and look forward to your kind reply!

**Comment by FangjinhuaWang** [comment]
Hi,

For our method, the performance is Acc./Comp/Overall: 0.458, 0.291, 0.374

**Comment by qtz980805** [comment]
Ok. Thanks a lot!
