### ISSUE TITLE
Version of MATLAB to evaluate

### ISSUE THREAD

**Issue by YuhsiHu** [FangjinhuaWang/PatchmatchNet#56]
Thank you for your project. What version of MATLAB do you use? When I use the evaluation code, I get an error that ‘KDTreeSearcher cannot be found’.

**Comment by FangjinhuaWang** [comment]
Hi,

I am using 2020b.

**Comment by YuhsiHu** [comment]
Thank you for sharing. After installing toolbox for statics and machine learning, everything went well.
