### ISSUE TITLE
eval_custom.py lost

### ISSUE THREAD

**Issue by MaybeOjbk** [FangjinhuaWang/PatchmatchNet#59]
hi,  I found the  /dataset/eval_custom.py  may be lost which you have mentioned in README.md ，would you  please upload it

**Comment by FangjinhuaWang** [comment]
Hi, the readme is not up-to-date. We will update the readme file soon.

**Comment by anmatako** [comment]
Readme update is in PR #60 currently. For the time being you can use the eval.py script for custom (and practically all) datasets.

**Comment by MaybeOjbk** [comment]
thank you very much!
