### ISSUE TITLE
Tensors left behind on CPU in DataParallel Implementation

### ISSUE THREAD

**Issue by yyeboah** [FangjinhuaWang/PatchmatchNet#61]
I am encountering an issue with tensors being left behind on the CPU, triggering an assertion error as follows: `AssertionError: Gather function not implemented for CPU tensors`. This is happening within the `process_sample` function. 

I can confirm that this is strictly associated with DataParallel since passing only a single CUDA device suppresses the error.

**Comment by anmatako** [comment]
@yyeboah How were you able to test execution on the CPU? Did you just use a machine without a GPU available? The setup of PatchMatchNet uses GPU by default (transfers tensors to device) and also enables data parallel by default assuming that all execution will be done on GPU. The model itself as provided by the TorchScript module checkpoint in `checkpoints/module_000007.pt` does not require DataParallel and can work on CPU execution (I tested that with my colmap integration). If you can provide more detail on your use-case, the specific setup of the machine you're testing, any code changes you made, and the error details I should be able to reproduce the issue and see if there's a good solution for this. Supporting CPU execution at least for evaluation seems like a valid use-case so if we can do this in a reasonable way it would be worth looking into it.

**Comment by yyeboah** [comment]
@anmatako Thank you for the response and my apologies for the brevity. Here is a little more context into what is happening.
I am training on a cluster of V100 GPUs(not CPUs), with Pytorch 1.7.1. I am able to load and run inference with the attached pretrained weights, and also able to train my own weights on my own dataset, albeit on a single GPU card (I simply expose a single GPU card to force training to only use one GPU). 

However, attempting to train across multiple GPUs triggers `AssertionError: Gather function not implemented for CPU tensors`, on the same machine where I successfully trained with single GPU. Reproducing the error should be straight-forward by attempting to train across multiple GPUs with the current implementation of DataParallel in the codebase. If this fails to reproduce the assertion error then it could be a Pytorch bug specific to my Pytorch build.

**Comment by anmatako** [comment]
@yyeboah Thank you for the additional context. Unfortunately, I have not trained on a multi-GPU environment, so I had no idea this assertion error can happen. Is there any additional info on the error regarding which gather function is failing? Ideally there should be no CPU tensors anywhere in PatchMatchNet so if the error relates to that it should be fairly easy to track it down and change these tensors to be on GPU.

**Comment by anmatako** [comment]
@yyeboah I created PR #62 to address the empty tensors potentially being created on the CPU and this could be the cause of the issue you're seeing. If you can grab the changes from that PR and test them out that would be great as I don't have a multi-GPU setup readily available to test this; it works of course on my single GPU machine.

**Comment by yyeboah** [comment]
@anmatako I have retrieved PR #62 and after testing,  I can confirm that indeed this issue has resolved. Cheers, and have a happy New year !
