### ISSUE TITLE
Reproduce on DTU 

### ISSUE THREAD

**Issue by ss2lyf** [FangjinhuaWang/PatchmatchNet#63]
Hi, I am trying to reproduce the results on the DTU data set recently, but the result I got with the weight of the current version is:
`acc.: 0.429597, comp.: 0.337553, overall: 0.383575`
Then I tried to run the weights you uploaded on May 24, 2021, and got the result:
`acc.: 0.428391, comp.: 0.279024, overall: 0.353707`
I don't know if these are caused by my running errors or because the new weights are quite different from the old weights. I wold like to know that can you provide the latest DTU eval results using the latest weights? thanks a lot!

**Comment by hx804722948** [comment]
hi, Which version of cuda and torch do you use

**Comment by anmatako** [comment]
@ss2lyf I think there is an issue with random generators not having a fixed seed and resulting weights may be slightly different. I think the version of CUDA and Torch used can affect that as well. @FangjinhuaWang what's your take here? If needed I should be able to re-create the eval results with the latest weights from the stored model. FYI I did the training on CUDA 11.1 with Torch 1.9.1.

**Comment by ss2lyf** [comment]
> hi, Which version of cuda and torch do you use

cuda11.1 and torch 1.9.0

**Comment by FangjinhuaWang** [comment]
Yes, in the original model, I forgot to fix the seed for random view [dtu_yao.py](https://github.com/FangjinhuaWang/PatchmatchNet/blob/82206d8b603ec925b6e4b1990618e0ad769347de/datasets/dtu_yao.py#L65). I think this will affect the training.

**Comment by ss2lyf** [comment]
> Yes, in the original model, I forgot to fix the seed for random view [dtu_yao.py](https://github.com/FangjinhuaWang/PatchmatchNet/blob/82206d8b603ec925b6e4b1990618e0ad769347de/datasets/dtu_yao.py#L65). I think this will affect the training.

Hi, I wold like to know that can you provide the latest DTU eval results using the latest weights? thanks a lot!

**Comment by xmlyqing00** [comment]
> > Yes, in the original model, I forgot to fix the seed for random view [dtu_yao.py](https://github.com/FangjinhuaWang/PatchmatchNet/blob/82206d8b603ec925b6e4b1990618e0ad769347de/datasets/dtu_yao.py#L65). I think this will affect the training.
> 
> Hi, I wold like to know that can you provide the latest DTU eval results using the latest weights? thanks a lot!

That would be very helpful :)

Happy new year!

**Comment by FangjinhuaWang** [comment]
Hi,

I think it is already posted by another contributor: [point clouds & metrics](https://microsoft-my.sharepoint.com/:u:/p/anmatako/EWzaqJRj6OVLhZwtNIaVO2YB3O1RI3nqTMl89303urDuDg?e=8rQCIH)

**Comment by ss2lyf** [comment]
> @FangjinhuaWang thank you for finding and sharing this data.

![image](https://user-images.githubusercontent.com/38303003/152298019-4fef2c84-fe5a-4300-8382-03e03abd648f.png)
Hi, I tried to click on the link, but I got the error as shown in the figure.

**Comment by ss2lyf** [comment]
> @FangjinhuaWang thank you for finding and sharing this data.

![image](https://user-images.githubusercontent.com/38303003/152298871-6544efd7-93b9-47b8-bf13-51ddd1a742cf.png)
Hi, I tried to click on the link, but I got the error as shown in the figure.

**Comment by anmatako** [comment]
@ss2lyf Sorry about that one. The share is a Microsoft location that likely does not allow access outside the organization. @FangjinhuaWang could you please upload the relevant file(s) in some ETH share if at all possible so that they are publicly accessible?

**Comment by anmatako** [comment]
Here's a link for the [new results](https://1drv.ms/u/s!AoP4EQugAoI2vAuOtb6eYdFtQFAh?e=ODEUcG). Let me know if this one works, otherwise I'll find an alternative location.

**Comment by ss2lyf** [comment]
> Here's a link for the [new results](https://1drv.ms/u/s!AoP4EQugAoI2vAuOtb6eYdFtQFAh?e=ODEUcG). Let me know if this one works, otherwise I'll find an alternative location.

yes，the files you share can be viewed normally，The files you share can be viewed normally. At the same time, I would like to ask if you can provide the GPU device and batch size used to get this weight. Thanks a lot!

**Comment by ss2lyf** [comment]
> @ss2lyf The batch size was 2 and the GPU I used was NVIDIA GeForce RTX 2080 Ti. Note that due to issues with the seeding that @FangjinhuaWang mentioned the results won't be identical even if the run is repeated on an identical setup.
Thanks a lot!

**Comment by TWang1017** [comment]
> Here's a link for the [new results](https://1drv.ms/u/s!AoP4EQugAoI2vAuOtb6eYdFtQFAh?e=ODEUcG). Let me know if this one works, otherwise I'll find an alternative location.

Hi, wondering why the final evaluation of the result in this link is acc 0.48 and comp 0.39 instead of the claimed acc 0.427 | comp 0.277
