### ISSUE TITLE
invalid input folder

### ISSUE THREAD

**Issue by gaofang-xsy** [FangjinhuaWang/PatchmatchNet#69]
hi there,thanks for your excellent work . I 'm a nerd in .net work,I download the DTU ,but when i try the sh eval.sh ,the problems came out like invalid input folder .I change the DTU_testing to the location of DTU.Hope for your answer.

**Comment by FangjinhuaWang** [comment]
Sorry for the late reply. Please change the folder names in the dataset from "cams_1" to "cams".
