### ISSUE TITLE
test on ETH3D dataset

### ISSUE THREAD

**Issue by JianfeiJ** [FangjinhuaWang/PatchmatchNet#73]
你好！
我使用提供的预训练模型在eth3d上进行测试，生成点云很奇怪。我该如何解决呢？

![Snipaste_2022-10-25_11-41-02](https://user-images.githubusercontent.com/98368257/197677097-ef798f4f-606c-4084-b809-d94f678eb19a.png)

**Comment by FangjinhuaWang** [comment]
你可以增大geo_mask_thres（geometrically view consistent的数量）来进一步滤除噪声
