### ISSUE TITLE
Depth images are empty with your checkpoint on dtu dataset

### ISSUE THREAD

**Issue by mtaktash** [FangjinhuaWang/PatchmatchNet#76]
Hi! When I try to reproduce your results with eval.sh script using your checkpoint and dtu eval set, I get empty depth maps and fused.ply files.

My images look like this (bottom is normalized to 0...1 to be an image)
<img width="653" alt="Screenshot 2022-10-26 at 12 25 07" src="https://user-images.githubusercontent.com/22811906/198014453-dbddab59-f750-4ce3-abee-e6e972496880.png">

Can you help to understand what is the issue?

**Comment by MabeNice** [comment]
Hi, I have met the same question. How did you solve it?

**Comment by MabeNice** [comment]
Hi, I have met the same question. How did you solve it? @mtaktash

**Comment by sysu19351072** [comment]
> Hi, I have met the same question. How did you solve it? @mtaktash

Have Solved by using provided DTU test
