### ISSUE TITLE
colmap_input.py outputs depth_min and depth_max units

### ISSUE THREAD

**Issue by Alive-zyxs** [FangjinhuaWang/PatchmatchNet#86]
Hi，I took a set of photos outdoors, the actual depth distance should be relatively large, but the depth_min and depth_max values after colmap_input.py conversion are very small, I think this value is more appropriate in meters.
![image](https://user-images.githubusercontent.com/119551869/234467788-5d3a6b9b-c5af-4833-a9f4-b7cd316cc907.png)

However, I noticed that the depth_min and depth_max of the dtu dataset are 425 and 935 respectively, and on some sources it is stated that their units are millimeters.

So I'm wondering, are depth_min and depth_max units fixed when colmap_input.py converts the output of colmap? Or are depth_min and depth_max just "relative values" that need to be converted later (such as multiplying by some value)?
Thank you very much for your outstanding work！Looking forward to your reply

**Comment by FangjinhuaWang** [comment]
colmap cannot give a metric such as meter since it is monocular SfM. The depth range of dtu dataset is manually set by MVSNet since the ground truth point cloud and pose are given

**Comment by Alive-zyxs** [comment]
Thanks for your reply! Since colmap doesn't give us the units of measure, does it mean that the depth_min and depth_max computed by colmap_input.py and the depth map inferred by patchmatchnet are also "relative values"? （Without units like meter or millimeter)

**Comment by FangjinhuaWang** [comment]
yes, exactly.
